language: python
python:
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install sphinx sphinx_rtd_theme
script: make -C doc html
after_success:
  - ./push.sh
env:
  global:
    - secure: "M2OshzQhT0GJKy57foLwjkikt4FGN+lKSLEdyfRHjzwQaNypi1q5WfD7mNbCwXEvQWD4hC0Sek2HAGnBAjK+Irg1xS32R4lqUNudJzD7D4hCm7xwJ3TehAiR+7kfPKzCVBV+TdYdeUqBsa284DWoZvrXpgASFz4LijhTR2LHb7g62YsS/K9TpagKBE3Wc6phasqGvzu2gXHY3xT0QyrJeeQlcfLWg77dY/EEIqJ1OomZh6XYAQNtEEQfLSLoRfyzFOxZyZ55PPmZPzLJqb3QT97Fcj2l6HGOJZ7hBel0UPQz1sGRTJ+6fg4fo4tn1MBWiM3pwaEJiinezwu9XE7K1RKm4/eZ1GHQaNDbBNlhLoJrvKgWmaTHW+dIdy+RWKl68PVdMSlIyM8WAEWFWs9FwS9EKYUXJdMEMxZ0jyzYKah/DHGIhtR1DdiMUG0cBBImdUoSGbe+GYjnuJn9rm+AC5utSYEfa+csBCWp7SczADJrtQU9pn5LfZdv9H1HaY8qO+LxfKj17HtlIYhuAQQM7sffHlp9SWYS+6Zk4MkXb8Q7b5jtpvAunegCAXMJN0uiySDGj4/6zv6L1Y4rnNJV2n6Gn35VDl1VmLiPwFbaBH/WbUglP+AzESdcFR6nh93lOF6Lq1pPNsGfhAeu29KLjV8HvLLULrhNKzPfYohk4qA="